/*
 * Get the name of the languae from the code
 */
function getLanguage(code) {
	var langs = {
		"abk":"Abkhaz",
		"ace":"Achinese",
		"ach":"Acoli",
		"ada":"Adangme",
		"ady":"Adygei",
		"aar":"Afar",
		"afh":"Afrihili (Artificial language)",
		"afr":"Afrikaans",
		"afa":"Afroasiatic (Other)",
		"ain":"Ainu",
		"aka":"Akan",
		"akk":"Akkadian",
		"alb":"Albanian",
		"ale":"Aleut",
		"alg":"Algonquian (Other)",
		"alt":"Altai",
		"tut":"Altaic (Other)",
		"amh":"Amharic",
		"anp":"Angika",
		"apa":"Apache languages",
		"ara":"Arabic",
		"arg":"Aragonese",
		"arc":"Aramaic",
		"arp":"Arapaho",
		"arw":"Arawak",
		"arm":"Armenian",
		"rup":"Aromanian",
		"art":"Artificial (Other)",
		"asm":"Assamese",
		"ath":"Athapascan (Other)",
		"aus":"Australian languages",
		"map":"Austronesian (Other)",
		"ava":"Avaric",
		"ave":"Avestan",
		"awa":"Awadhi",
		"aym":"Aymara",
		"aze":"Azerbaijani",
		"ast":"Bable",
		"ban":"Balinese",
		"bat":"Baltic (Other)",
		"bal":"Baluchi",
		"bam":"Bambara",
		"bai":"Bamileke languages",
		"bad":"Banda languages",
		"bnt":"Bantu (Other)",
		"bas":"Basa",
		"bak":"Bashkir",
		"baq":"Basque",
		"btk":"Batak",
		"bej":"Beja",
		"bel":"Belarusian",
		"bem":"Bemba",
		"ben":"Bengali",
		"ber":"Berber (Other)",
		"bho":"Bhojpuri",
		"bih":"Bihari (Other)",
		"bik":"Bikol",
		"byn":"Bilin",
		"bis":"Bislama",
		"zbl":"Blissymbolics",
		"bos":"Bosnian",
		"bra":"Braj",
		"bre":"Breton",
		"bug":"Bugis",
		"bul":"Bulgarian",
		"bua":"Buriat",
		"bur":"Burmese",
		"cad":"Caddo",
		"car":"Carib",
		"cat":"Catalan",
		"cau":"Caucasian (Other)",
		"ceb":"Cebuano",
		"cel":"Celtic (Other)",
		"cai":"Central American Indian (Other)",
		"chg":"Chagatai",
		"cmc":"Chamic languages",
		"cha":"Chamorro",
		"che":"Chechen",
		"chr":"Cherokee",
		"chy":"Cheyenne",
		"chb":"Chibcha",
		"chi":"Chinese",
		"chn":"Chinook jargon",
		"chp":"Chipewyan",
		"cho":"Choctaw",
		"chu":"Church Slavic",
		"chk":"Chuukese",
		"chv":"Chuvash",
		"cop":"Coptic",
		"cor":"Cornish",
		"cos":"Corsican",
		"cre":"Cree",
		"mus":"Creek",
		"crp":"Creoles and Pidgins (Other)",
		"cpe":"Creoles and Pidgins, English-based (Other)",
		"cpf":"Creoles and Pidgins, French-based (Other)",
		"cpp":"Creoles and Pidgins, Portuguese-based (Other)",
		"crh":"Crimean Tatar",
		"hrv":"Croatian",
		"cus":"Cushitic (Other)",
		"cze":"Czech",
		"dak":"Dakota",
		"dan":"Danish",
		"dar":"Dargwa",
		"day":"Dayak",
		"del":"Delaware",
		"din":"Dinka",
		"div":"Divehi",
		"doi":"Dogri",
		"dgr":"Dogrib",
		"dra":"Dravidian (Other)",
		"dua":"Duala",
		"dut":"Dutch",
		"dum":"Dutch, Middle (ca. 1050-1350)",
		"dyu":"Dyula",
		"dzo":"Dzongkha",
		"frs":"East Frisian",
		"bin":"Edo",
		"efi":"Efik",
		"egy":"Egyptian",
		"eka":"Ekajuk",
		"elx":"Elamite",
		"eng":"English",
		"enm":"English, Middle (1100-1500)",
		"ang":"English, Old (ca. 450-1100)",
		"myv":"Erzya",
		"epo":"Esperanto",
		"est":"Estonian",
		"gez":"Ethiopic",
		"ewe":"Ewe",
		"ewo":"Ewondo",
		"fan":"Fang",
		"fat":"Fanti",
		"fao":"Faroese",
		"fij":"Fijian",
		"fil":"Filipino",
		"fin":"Finnish",
		"fiu":"Finno-Ugrian (Other)",
		"fon":"Fon",
		"fre":"French",
		"frm":"French, Middle (ca. 1300-1600)",
		"fro":"French, Old (ca. 842-1300)",
		"fry":"Frisian",
		"fur":"Friulian",
		"ful":"Fula",
		"gaa":"Gã",
		"glg":"Galician",
		"lug":"Ganda",
		"gay":"Gayo",
		"gba":"Gbaya",
		"geo":"Georgian",
		"ger":"German",
		"gmh":"German, Middle High (ca. 1050-1500)",
		"goh":"German, Old High (ca. 750-1050)",
		"gem":"Germanic (Other)",
		"gil":"Gilbertese",
		"gon":"Gondi",
		"gor":"Gorontalo",
		"got":"Gothic",
		"grb":"Grebo",
		"grc":"Greek, Ancient (to 1453)",
		"gre":"Greek, Modern (1453-)",
		"grn":"Guarani",
		"guj":"Gujarati",
		"gwi":"Gwich'in",
		"hai":"Haida",
		"hat":"Haitian French Creole",
		"hau":"Hausa",
		"haw":"Hawaiian",
		"heb":"Hebrew",
		"her":"Herero",
		"hil":"Hiligaynon",
		"hin":"Hindi",
		"hmo":"Hiri Motu",
		"hit":"Hittite",
		"hmn":"Hmong",
		"hun":"Hungarian",
		"hup":"Hupa",
		"iba":"Iban",
		"ice":"Icelandic",
		"ido":"Ido",
		"ibo":"Igbo",
		"ijo":"Ijo",
		"ilo":"Iloko",
		"smn":"Inari Sami",
		"inc":"Indic (Other)",
		"ine":"Indo-European (Other)",
		"ind":"Indonesian",
		"inh":"Ingush",
		"ina":"Interlingua (International Auxiliary Language Association)",
		"ile":"Interlingue",
		"iku":"Inuktitut",
		"ipk":"Inupiaq",
		"ira":"Iranian (Other)",
		"gle":"Irish",
		"mga":"Irish, Middle (ca. 1100-1550)",
		"sga":"Irish, Old (to 1100)",
		"iro":"Iroquoian (Other)",
		"ita":"Italian",
		"jpn":"Japanese",
		"jav":"Javanese",
		"jrb":"Judeo-Arabic",
		"jpr":"Judeo-Persian",
		"kbd":"Kabardian",
		"kab":"Kabyle",
		"kac":"Kachin",
		"kal":"Kalâtdlisut",
		"kam":"Kamba",
		"kan":"Kannada",
		"kau":"Kanuri",
		"kaa":"Kara-Kalpak",
		"krc":"Karachay-Balkar",
		"krl":"Karelian",
		"kar":"Karen languages",
		"kas":"Kashmiri",
		"csb":"Kashubian",
		"kaw":"Kawi",
		"kaz":"Kazakh",
		"kha":"Khasi",
		"khm":"Khmer",
		"khi":"Khoisan (Other)",
		"kho":"Khotanese",
		"kik":"Kikuyu",
		"kmb":"Kimbundu",
		"kin":"Kinyarwanda",
		"tlh":"Klingon (Artificial language)",
		"kom":"Komi",
		"kon":"Kongo",
		"kok":"Konkani",
		"kut":"Kootenai",
		"kor":"Korean",
		"kos":"Kosraean",
		"kpe":"Kpelle",
		"kro":"Kru (Other)",
		"kua":"Kuanyama",
		"kum":"Kumyk",
		"kur":"Kurdish",
		"kru":"Kurukh",
		"kir":"Kyrgyz",
		"lad":"Ladino",
		"lah":"Lahndā",
		"lam":"Lamba (Zambia and Congo)",
		"lao":"Lao",
		"lat":"Latin",
		"lav":"Latvian",
		"lez":"Lezgian",
		"lim":"Limburgish",
		"lin":"Lingala",
		"lit":"Lithuanian",
		"jbo":"Lojban (Artificial language)",
		"nds":"Low German",
		"dsb":"Lower Sorbian",
		"loz":"Lozi",
		"lub":"Luba-Katanga",
		"lua":"Luba-Lulua",
		"lui":"Luiseño",
		"smj":"Lule Sami",
		"lun":"Lunda",
		"luo":"Luo (Kenya and Tanzania)",
		"lus":"Lushai",
		"ltz":"Luxembourgish",
		"mas":"Maasai",
		"mac":"Macedonian",
		"mad":"Madurese",
		"mag":"Magahi",
		"mai":"Maithili",
		"mak":"Makasar",
		"mlg":"Malagasy",
		"may":"Malay",
		"mal":"Malayalam",
		"mlt":"Maltese",
		"mnc":"Manchu",
		"mdr":"Mandar",
		"man":"Mandingo",
		"mni":"Manipuri",
		"mno":"Manobo languages",
		"glv":"Manx",
		"mao":"Maori",
		"arn":"Mapuche",
		"mar":"Marathi",
		"chm":"Mari",
		"mah":"Marshallese",
		"mwr":"Marwari",
		"myn":"Mayan languages",
		"men":"Mende",
		"mic":"Micmac",
		"min":"Minangkabau",
		"mwl":"Mirandese",
		"mis":"Miscellaneous languages",
		"moh":"Mohawk",
		"mdf":"Moksha",
		"mkh":"Mon-Khmer (Other)",
		"lol":"Mongo-Nkundu",
		"mon":"Mongolian",
		"mos":"Mooré",
		"mul":"Multiple languages",
		"mun":"Munda (Other)",
		"nqo":"N'Ko",
		"nah":"Nahuatl",
		"nau":"Nauru",
		"nav":"Navajo",
		"nbl":"Ndebele (South Africa)",
		"nde":"Ndebele (Zimbabwe)",
		"ndo":"Ndonga",
		"nap":"Neapolitan Italian",
		"nep":"Nepali",
		"new":"Newari",
		"nwc":"Newari, Old",
		"nia":"Nias",
		"nic":"Niger-Kordofanian (Other)",
		"ssa":"Nilo-Saharan (Other)",
		"niu":"Niuean",
		"zxx":"No linguistic content",
		"nog":"Nogai",
		"nai":"North American Indian (Other)",
		"frr":"North Frisian",
		"sme":"Northern Sami",
		"nso":"Northern Sotho",
		"nor":"Norwegian",
		"nob":"Norwegian (Bokmål)",
		"nno":"Norwegian (Nynorsk)",
		"nub":"Nubian languages",
		"nym":"Nyamwezi",
		"nya":"Nyanja",
		"nyn":"Nyankole",
		"nyo":"Nyoro",
		"nzi":"Nzima",
		"oci":"Occitan (post-1500)",
		"xal":"Oirat",
		"oji":"Ojibwa",
		"non":"Old Norse",
		"peo":"Old Persian (ca. 600-400 B.C.)",
		"ori":"Oriya",
		"orm":"Oromo",
		"osa":"Osage",
		"oss":"Ossetic",
		"oto":"Otomian languages",
		"pal":"Pahlavi",
		"pau":"Palauan",
		"pli":"Pali",
		"pam":"Pampanga",
		"pag":"Pangasinan",
		"pan":"Panjabi",
		"pap":"Papiamento",
		"paa":"Papuan (Other)",
		"per":"Persian",
		"phi":"Philippine (Other)",
		"phn":"Phoenician",
		"pon":"Pohnpeian",
		"pol":"Polish",
		"por":"Portuguese",
		"pra":"Prakrit languages",
		"pro":"Provençal (to 1500)",
		"pus":"Pushto",
		"que":"Quechua",
		"roh":"Raeto-Romance",
		"raj":"Rajasthani",
		"rap":"Rapanui",
		"rar":"Rarotongan",
		"roa":"Romance (Other)",
		"rom":"Romani",
		"rum":"Romanian",
		"run":"Rundi",
		"rus":"Russian",
		"sal":"Salishan languages",
		"sam":"Samaritan Aramaic",
		"smi":"Sami",
		"smo":"Samoan",
		"sad":"Sandawe",
		"sag":"Sango (Ubangi Creole)",
		"san":"Sanskrit",
		"sat":"Santali",
		"srd":"Sardinian",
		"sas":"Sasak",
		"sco":"Scots",
		"gla":"Scottish Gaelic",
		"sel":"Selkup",
		"sem":"Semitic (Other)",
		"srp":"Serbian",
		"srr":"Serer",
		"shn":"Shan",
		"sna":"Shona",
		"iii":"Sichuan Yi",
		"scn":"Sicilian Italian",
		"sid":"Sidamo",
		"sgn":"Sign languages",
		"bla":"Siksika",
		"snd":"Sindhi",
		"sin":"Sinhalese",
		"sit":"Sino-Tibetan (Other)",
		"sio":"Siouan (Other)",
		"sms":"Skolt Sami",
		"den":"Slavey",
		"sla":"Slavic (Other)",
		"slo":"Slovak",
		"slv":"Slovenian",
		"sog":"Sogdian",
		"som":"Somali",
		"son":"Songhai",
		"snk":"Soninke",
		"wen":"Sorbian (Other)",
		"sot":"Sotho",
		"sai":"South American Indian (Other)",
		"sma":"Southern Sami",
		"spa":"Spanish",
		"srn":"Sranan",
		"suk":"Sukuma",
		"sux":"Sumerian",
		"sun":"Sundanese",
		"sus":"Susu",
		"swa":"Swahili",
		"ssw":"Swazi",
		"swe":"Swedish",
		"gsw":"Swiss German",
		"syc":"Syriac",
		"syr":"Syriac, Modern",
		"tgl":"Tagalog",
		"tah":"Tahitian",
		"tai":"Tai (Other)",
		"tgk":"Tajik",
		"tmh":"Tamashek",
		"tam":"Tamil",
		"tat":"Tatar",
		"tel":"Telugu",
		"tem":"Temne",
		"ter":"Terena",
		"tet":"Tetum",
		"tha":"Thai",
		"tib":"Tibetan",
		"tig":"Tigré",
		"tir":"Tigrinya",
		"tiv":"Tiv",
		"tli":"Tlingit",
		"tpi":"Tok Pisin",
		"tkl":"Tokelauan",
		"tog":"Tonga (Nyasa)",
		"ton":"Tongan",
		"tsi":"Tsimshian",
		"tso":"Tsonga",
		"tsn":"Tswana",
		"tum":"Tumbuka",
		"tup":"Tupi languages",
		"tur":"Turkish",
		"ota":"Turkish, Ottoman",
		"tuk":"Turkmen",
		"tvl":"Tuvaluan",
		"tyv":"Tuvinian",
		"twi":"Twi",
		"udm":"Udmurt",
		"uga":"Ugaritic",
		"uig":"Uighur",
		"ukr":"Ukrainian",
		"umb":"Umbundu",
		"und":"Undetermined",
		"hsb":"Upper Sorbian",
		"urd":"Urdu",
		"uzb":"Uzbek",
		"vai":"Vai",
		"ven":"Venda",
		"vie":"Vietnamese",
		"vol":"Volapük",
		"vot":"Votic",
		"wak":"Wakashan languages",
		"wln":"Walloon",
		"war":"Waray",
		"was":"Washoe",
		"wel":"Welsh",
		"him":"Western Pahari languages",
		"wal":"Wolayta",
		"wol":"Wolof",
		"xho":"Xhosa",
		"sah":"Yakut",
		"yao":"Yao (Africa)",
		"yap":"Yapese",
		"yid":"Yiddish",
		"yor":"Yoruba",
		"ypk":"Yupik languages",
		"znd":"Zande languages",
		"zap":"Zapotec",
		"zza":"Zaza",
		"zen":"Zenaga",
		"zha":"Zhuang",
		"zul":"Zulu",
		"zun":"Zuni"
	}
	return langs[code];
}

/*
 * Basic tag layout for a single piece of data
 *
 * prop: 	Name of Schema.org property
 * content: Input data being associate with prop
 * meta: 	Boolean that is true if we are building a metadata tag, and false if we are creating visible content 
 * label: 	What kind of content is being displayed 
 */
function buildTag(prop,content,meta,label) {
	if (meta) {
		return '\t\t<meta itemprop="' + prop + '" content="' + content + '"/>\n';
	}
	else {
		return '\t\t\t<dt>' + label + ':</dt>\n\t\t\t<dd itemprop="' + prop + '"><b>' + content + '</b></dd>\n';
	}
}

function buildItemscopeTag(prop,type,content) {
	return '\t\t\t<div itemprop="' + prop + '" itemscope itemtype="' + type + '">\n' + content + '\t\t\t</div>\n';
}

/*
 * For labeling an element wtih a Scehema.org property when the element is part of an atypical HTML tag, and 
 * embeded umong other information
 *
 * prop: 	Name of the Schema.org property
 * content: Input data being associated with prop
 */
function buildSpan(prop,content) {
	return '<span itemprop="' + prop + '">' + content + '</span>';
}

/*
 * Create a new div for each person listed as a contributer, switching the itemscope to person. Separately label
 * the family name and given name.
 */
function listPerson(family,given,role) {
	var output_string = '\t\t\t<div itemprop="author" itemscope itemtype="http://schema.org/Person">\n';
	output_string += '\t\t\t\t<dt>Author:</dt>\n';
	output_string += '\t\t\t\t<dd><b>';
	if (checkExists(family) && checkExists(given)) {
		output_string += buildSpan('familyName',family) + ', ' + buildSpan('givenName',given);
	}
	else if (checkExists(family) || checkExists(given)) {
		if (checkExists(family)) {
			output_string += buildSpan('familyName',family);
		}
		else {
			output_string += buildSpan('givenName',given);
		}
	}
	output_string += '</b></dd>\n';
	output_string += '\t\t\t</div>\n';
	return output_string;
}

/*
 * Build an HTML page with Schema.org labels for the content. Two strings are maintained: metaTags holds metadata that
 * the page will be associated with on search, but displayes no content. displayTags holds the content that is viewable
 * in a browser, with the appropriate content being labeled. At the end the two strings are combined into the text string
 *
 * record: 			 object containing the user-input data
 * institution_info: object containing name of institution creating record
 */
function downloadHTML(record,institution_info) {
	var metaTags = '';
	var displayTags = '';

	metaTags += buildTag('inLanguage',record.language,true,'');

	displayTags += buildTag('name',record.title,false,'Title');

	displayTags += listPerson(record.author['family'],record.author['given']);

	displayTags += buildTag('publisher','University of Illinois at Urbana-Champaign',false,'Publisher');

	var content = '';
	content += '<span itemprop="addressLocality">Urbana</span>, <span itemprop="addressRegion">Ill.</span>';
	var publication_location = buildItemscopeTag('publication','http://schema.org/PublicationEvent',buildItemscopeTag('location','http://schema.org/PostalAddress','\t\t\t\t<dt>Publication Location:</dt>\n\t\t\t\t<dd><b>' + content + '</b></dd>\n'));
	displayTags += publication_location;

	displayTags += buildTag('datePublished',record.publication_year,false,'Date of Publication');

	displayTags += '\t\t\t<dt>Physical Description:</dt>\n\t\t\t<dd><b>' + buildSpan('numberOfPages',record.number_of_pages) + ' ' + record.leaf_or_page;
	if (checkExists(record.illustrations_yes) && record.illustrations_yes == true) {
		displayTags += '; illustrations';
	}
	displayTags += '</b></dd>\n';

	displayTags += '\t\t\t<dt>Language:</dt>\n\t\t\t<dd><b>' + getLanguage(record.language) + '</b></dd>\n';

	displayTags += '\t\t\t<dt>Thesis:</dt>\n\t\t\t<dd><b>Thesis (' + record.major + ')-- University of Illinois at Urbana-Champaign, ' + record.publication_year + '.</b></dd>\n';

	displayTags += '\t\t\t<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">\n\t\t\t\t<dt>Located At:</dt>\n\t\t\t\t<dd><b><span itemprop="seller" href="' + institution_info['html']['url'] + '">' + institution_info['html']['name'] + '</span></b></dd>\n\t\t\t</div>\n'; 

	var text = '<!DOCTYPE html>\n<html>\n<head>\n	<meta charset="utf-8">\n</head>\n\n<body>\n\t<div itemscope itemtype="http://schema.org/Book">\n' + metaTags + '\t\t<dl>\n' + displayTags + '\t\t</dl>\n\t</div>\n</body>\n</html>';
	downloadFile(text,'html');
}